name: React Vite CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 23.x]  # Specify Node.js versions to test against

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci  # Uses package-lock.json for exact versions

    - name: Lint check
      run: |
        npm run lint || true  # Add '|| true' if you haven't set up linting yet

    - name: Run tests
      run: |
        npm run test || true  # Add '|| true' if you haven't set up tests yet

    - name: Build
      run: npm run build

    # Optional: Cache the build output
    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          dist
          .cache
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-

    # Optional: Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: dist/